### ISSUE TITLE
AttributeError: 'unicode' object has no attribute '_sort_key'

### ISSUE THREAD

**Issue by mingtak** [zopefoundation/z3c.relationfield#1]
whan I write a custom dexterity style's relationfield, like as

```
classcod = RelationChoice(
    title=_(u"Classification Code"),
    vocabulary="plone.app.vocabularies.Catalog",
    required=False,
)
```

have a error as above:

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in **call**
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.edit, line 65, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in **call**
  Module z3c.form.button, line 170, in **call**
  Module plone.dexterity.browser.edit, line 29, in handleApply
  Module z3c.form.group, line 126, in applyChanges
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module plone.dexterity.content, line 759, in reindexOnModify
  Module Products.CMFCore.CMFCatalogAware, line 88, in reindexObject
  Module Products.CMFCore.CatalogTool, line 301, in reindexObject
  Module Products.CMFPlone.CatalogTool, line 345, in catalog_object
  Module Products.ZCatalog.ZCatalog, line 476, in catalog_object
  Module Products.ZCatalog.Catalog, line 360, in catalogObject
  Module Products.PluginIndexes.common.UnIndex, line 216, in index_object
  Module Products.PluginIndexes.common.UnIndex, line 242, in _index_object
  Module Products.PluginIndexes.common.UnIndex, line 193, in insertForwardIndexEntry
  Module z3c.relationfield.relation, line 87, in __cmp__
AttributeError: 'unicode' object has no attribute '_sort_key'

I fixed this error as above:
https://github.com/mingtak/z3c.relationfield/blob/master/src/z3c/relationfield/relation.py#L78
FYR, Thanks.

**Comment by mingtak** [comment]
note: this error happen in plone 5

**Comment by rodfersou** [comment]
@faassen could you please take a look at this problem with unicode object comparisons?

There is a failing PR here, and there are more people looking for the fix at #plone channel

**Comment by icemac** [comment]
@rodfersou I fixed master after a rebase of the PR to the master we could see if it passes the tests.

**Comment by icemac** [comment]
I am closing this old issue. Feel free to re-open it if there are any news about the topic.
