### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.relationfield#14]
See https://travis-ci.org/zopefoundation/z3c.relationfield/jobs/458285105

**Comment by mgedmin** [comment]
```
Expected:
    [<RelationValue object at ...>]
Got:
    [<z3c.relationfield.relation.RelationValue object at 0x7fc3e60c8140 oid 0x17 in <Connection at 7fc3e5e8e710>>]
```

Probably related to the recent `Persistent.__repr__` changes in persistent 4.4.0 (and 4.4.3).

**Comment by ale-rt** [comment]
I usually take care of this kind of things with a doccheker https://github.com/plone/plone.app.viewletmanager/blob/3a4fa62913c222c41442e51d7b6f6417a41edb88/plone/app/viewletmanager/tests/test_docs.py#L16

**Comment by icemac** [comment]
Maybe a `docchecker` is a bit of an overkill here. It should be enough to change the tests to the expected output and require `persistent >= 4.4.3`.

**Comment by icemac** [comment]
Travis CI is now green, see https://travis-ci.org/zopefoundation/z3c.relationfield
