### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.relationfield#23]
I'd like to cut a new release of this package. Could you please add me (`icemac`) as maintainer on PyPI?

**Comment by mauritsvanrees** [comment]
Invitation sent.

**Comment by icemac** [comment]
@mauritsvanrees Thank you. I just released https://pypi.org/project/z3c.relationfield/1.0/

**Comment by icemac** [comment]
I saw that [z3c.relationfield](https://github.com/zopefoundation/z3c.relationfield) is based on zc.relation which is currently archived because it seems to be broken and no-one cares. I am going unarchive it.
