### ISSUE TITLE
Uses BTrees wrongly, breaks when Interfaces stop being available

### ISSUE THREAD

**Issue by do3cc** [zopefoundation/z3c.relationfield#3]
Unfortunately, I could not find all kind of problems related to this, but this far I got:
The RelationCatalog stores InterfaceClasses in Btrees. These Interface class implementations can get lost if a package gets really uninstalled. ZODB in such a case manages, and creates a dynamic class on the fly. It has ZODB.Brocken or something in its **mro**. These classes have a different sort order and won't be found in BTrees any longer.
They appear in the BTree if you iterate over it, but you won't get it via getitem.
You could repair it by creating copies, but then you cannot store the RelationCatalog in the ZODB, because it won't store broken objects.
This package should either be able to handle the case of missing classes, or have repair methods or stops using classes that can change between restarts.

**Comment by icemac** [comment]
I am closing this old issue. Feel free to re-open it if there are any news about the topic.
