### ISSUE TITLE
Still uses BTrees wrongly, screws up people changing Interfaces.

### ISSUE THREAD

**Issue by do3cc** [zopefoundation/z3c.relationfield#4]
I started to document the bug and my workarounds here:
https://github.com/collective/plone.app.imagecropping/issues/69
I also started a discussion about the BTrees misbehaviour here: 
https://community.plone.org/t/request-for-comments-reducing-functionality-of-z3c-relationfield/1247
I wrote a hacky script to try to fix the issue where an interface has been renamed. 
The package in question did a reindex to make sure that the catalog stores the new interfaces, the event handlers of z3c.relationfield do not update all fields as required. But my suggestion is to actually stop storing Interfaces in the relation catalog.
Here is my fix gist: https://gist.github.com/do3cc/3ae985653b23ac63be0a
HTH someone

**Comment by icemac** [comment]
I am closing this old issue. Feel free to re-open it if there are any news about the topic.
