### ISSUE TITLE
RelationList and wrong permissions for custom content type

### ISSUE THREAD

**Issue by mgogoulos** [zopefoundation/z3c.relationfield#5]
Hi all, 

I have a simple content type with a few fields one of which uses RelationList to relate to items of another content type. As a simple user I can create the content type, and select the related items. This is saved ok, however if I edit the content type the list is empty . If I assign the role 'manager' to the user, then if I edit the content type I can see the items (as expected). 
How can I set the correct permission so that editing as a user would contain the items? I tried to find anything related inside the ZMI and sections as security/workflow/permissions etc but this hasn't worked for me. 

Any suggestions highly welcome. 

```
from z3c.relationfield.schema import RelationList

class ILecture(form.Schema):

    form.widget(relatedItems=QuerySourceFieldCheckboxWidget)
    relatedItems = RelationList(
            title=u"Clips",
            description=,
            default=[],
            value_type=RelationChoice(title=_(u"Related"),
                       source=ObjPathSourceBinder(object_provides=IPlumiVideo.__identifier__)),
            required=True,
       )

```

**Comment by do3cc** [comment]
I fear this is a real issue in that it may be that security is not always taken into full consideration and that the UI does also not have special handling for users who area only allowed to see some of the related objects. IOW, that might be a bigger task. Then again I only speak from my memory, maybe I am wrong and this security thing is always handled properly, but I doubt it :-(

**Comment by mgogoulos** [comment]
Thanks for the quick reply! So this has occurred to criticalcommons.org project - https://github.com/plumi/criticalcommons.content which is based on Plumi. The add/edit forms are Plone generic, as a simple user I can add the lecture content type, and select related items (which are not owned by me, but are on public state. I cannot see items that are private). But on edit they are not there anymore. 
As a portal admin I can edit that user's lecture content type and the related items are there. 

So any workaround that enables the user to see the related items for the lectures he creates would be ideal for me.

Thanks and regards

**Comment by icemac** [comment]
I am closing this old issue. Feel free to re-open it if there are any news about the topic.

**Comment by mgogoulos** [comment]
That was a blast from the past ;)
